### ISSUE TITLE
sorry to ask but how does it compare to diff-dom ?

### ISSUE THREAD

**Issue by kapouer** [WebReflection/udomdiff#13]
The domdiff/udomdiff API is somewhat very hard to understand:
why parent, currentNodes, futureNodes ?
why not source -> target ?
what is the meaning of "a callback to retrieve the node" ?
and wtf is "before" ?
This is really obscure... when compared to another dom diffing library like diff-dom.

**Comment by WebReflection** [comment]
what's diff-dom?

to answer:

  * currentNodes are those you own as content
  * futureNodes are those you are diffing as new result for that diff
  * the callback is used to retrieve persistent fragments, it's irrelevant if you don't have persistent fragments in your logic, hence optional for that reason
  * before is a node used as *pin* to perform operations around ... let me expand:

You have this content:

```html
<table>
  <tbody>
    <!--pin-->
  </tbody>
</table>
```

you want to populate that table out of an array of `TR` and you need to pin those diffs within that table ... how would you do that? You can't, you need a pinned node in the right place to add, remove, change, all *TRs* in there, and that *before* node ensures all your operations are confined within that context, otherwise lost while diffing.

This is why this signature has optional valure to pass: you know what you are doing and why? you use those ... you don't? just stick with the fact to change nodes in a container you need a parentNode, a previous list of content you had in there, and the future list of content you want in there after ... that's it.
