### ISSUE TITLE
Unnecessary (?) extra move operation

### ISSUE THREAD

**Issue by mindplay-dk** [WebReflection/udomdiff#7]
Hey,

I've been testing out some diffing algos, curious to see which DOM operations they actually perform.

One of the libraries I tested was this one, and I've come across a case where it seems to do an unnecessary DOM operation.

Here's my test bench:

https://jsfiddle.net/mindplay/o4gbaqw0/

I've added `console.log` statements for every DOM operation - you can press the buttons to perform various array operations to change the sorting of the elements, and then watch the console output for the exact DOM operations resulting from the diff operation from one state to the next.

It looks good for all operations except "Rotate Up" - which basically means, "take the first item on the list and move it to the bottom", which should be doable with a single `insertBefore`.

Instead, the result is two operations - a seemingly unnecessary `replaceChild` operation, followed by the expected `insertBefore` operation. (The resulting DOM state is correct though.)

With devtools open, you can see two nodes are being affected:

![image](https://user-images.githubusercontent.com/103348/114147400-f5fa0480-9918-11eb-8480-b74817499e71.png)

It isn't explicitly stated in the README of either this project or the original `domdiff`, but presumably the point of diffing is to perform as few DOM operations as possible? Just figured I'd report my findings, in case you do consider this a subtle "bug". 🙂

**Comment by WebReflection** [comment]
@mindplay-dk this project is already one of the fastest (if not the fastest) [out there](https://github.com/luwes/js-diff-benchmark/issues/41), but it's based on a best-effort compromise to be [the smallest](https://webreflection.medium.com/the-web-smallest-dom-diffing-library-5b69ac4d1f4d) once minified.

Accordingly, while it grants correct results, it might not do the best possible move for each specific use case, as knowing specific use cases ahead of time is very difficult if production size matters, so that unless you have an idea on how to fix this without compromising the production size, I'm afraid I have little interest in fixing this, 'cause *uhtml* and libraries based, behind the scene, on this project, are already one of the fastest of their kind (if not the fastest) and the focus is also in production size.

As summary, I don't consider this a bug, rather a best-effort/compromise intended behavior that produces, anyway, the final, expected, result, for a single case (edge or not) that's not super interesting to optimize unless the size remains the same, or smaller.

**Comment by mindplay-dk** [comment]
This issue isn't about size or speed. 🙂

The reason we diff at all, is to avoid things like loss of focus, iframes reloading, etc.

But that's totally fine, I understand you have different goals - and I have no idea how to fix this. 😄

**Comment by WebReflection** [comment]
There's no loss of focus or anything else if you don't change nodes ... if you do, there's no solution ... if you don't, and the input never leaves the DOM, you have zero issues whatsoever.

The goal is to have the best speed/size compromise in a library ... feel free to use another one, or maybe show a real-world case where you have issues with the current diffing, as I've never had one.

**Comment by WebReflection** [comment]
P.S. there are dozen examples with inputs, buttons, textareas, etc, in uhtml repository ... none of them suffer any issue of focus loss whatsoever, so unless you have some code I can help you with, I am not sure what you expect me to fix :man_shrugging:

**Comment by mindplay-dk** [comment]
No, it's not likely cause any issues in the real world.

> There's no loss of focus or anything else if you don't change nodes 

Yeah, so moving an element from top to bottom would cause the bottom node to change. If you had, say, a list of elements, and the last one contains a YouTube player or something else with an iframe, it would unexpectedly reload.

It's mostly on the matter of principle: if you didn't care about doing the minimum number of DOM changes, you wouldn't have to diff - you could just appendChild all children and be done with it, right?

I'd wanna get this right.

That's just me though, you don't have to agree, and as said, it's fine if you have different objectives 🙂

**Comment by WebReflection** [comment]
> if you didn't care about doing the minimum number of DOM changes, you wouldn't have to diff - you could just appendChild all children and be done with it, right?

This is the fourth differ I write because just appending nodes would be a perf killer plus I've already [linked benchmarks](https://github.com/luwes/js-diff-benchmark#browser-results-chrome-89-6x-cpu-throttling) where this library wins.

Again: if you feel so entitled to judge this library, my objectives, my way of working, you can stop using anything I'm doing right now, or maybe help out proposing the change that won't bloat the size and will do everything perfectly for use cases never seen to date live.

I am also closing this as I don't really have time for these conversations, but I'll review and, eventually, approve, a Merge Request with your perfect changes in it, 'cause this has zero priority to me and nobody ever complained ... and there's no real-world use case out there for me to consider fixing anything.

Take care.
