### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by titoBouzout** [WebReflection/udomdiff#9]
Would be possible to add some benchmarks to the repo if you have the code ? I have tried udomdiff a couple of times but surprisingly it's slightly slower. Which is highly suspicious or what I am doing is just faster _in some situations_. Even if I don't use I would love to give ideas to improve its speed when in scope of what you expect from this lib.

With some benchmark added I could test implementations and show off situations that you may consider improving.  For example if diffing is only about removals this may be faster(or maybe not) but you will get an idea of what I am thinking

```js
export function remove(prev = [], node = []) {
	for (let i = 0, item; i < prev.length; i++) {
		item = prev[i]
		item &&
			(node.length === 0 || !node.includes(item)) &&
			item.remove()
	}
	return node
}
```

**Comment by WebReflection** [comment]
that doesn't re-order items but *udomdiff* is a general purpose differ with extra features for persistent fragments, pinned diffs (before a node in between a list of nodes) and so on.

If you need to remove all nodes there's nothing faster than `parent.replaceChildren()` and if you need to always just append a node there's nothing faster than `parent.appendChild(node)` ... if you have an always same ordered list of nodes where you either append or remove but never swap or change nodes positions there's nothing faster than just use Set difference and remove it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference ... and because "*it depends*" this library tries to use heuristic to understand use cases but some heuristic is slower than manual changes because of course if you know already what to remove you can just splice the retained list of nodes and remove each spliced node after ... 

that being said, in [js-framework-benchmark](https://krausest.github.io/js-framework-benchmark/current.html) you can see *uhtml* smoking many famous alternatives and that's all thanks to *udomdiff* but when *domdiff* only was in that table is was closer to vanilla JS than any other library and this variant is actually faster than the older *domdiff*.

That being said, there is one benchmark in the test folder: `node test/js-diff-benchmark.js`

![Screenshot from 2024-04-17 13-22-57](https://github.com/WebReflection/udomdiff/assets/85749/a34a4099-9e2b-471f-aa75-059c48c6093b)

**Comment by titoBouzout** [comment]
> that doesn't re-order items... 

Yeah, I know ..xD I meant it to be as an example of some possible optimization. I knew it was a bad idea to give you some code example. 

> that being said, in [js-framework-benchmark](https://krausest.github.io/js-framework-benchmark/current.html) you can see uhtml smoking many famous alternatives

The test I am running is the js benchmark, and when I use udomdiff my test runs slower than using my approach. The problem of quoting the benchmark for this case is that in the swap rows there are more stuff happening not just swapping. 

Thanks for `difference` hint, I will try it out, but I am mostly sure it will be slower because creating both sets will be slower than just checking whats not in the other array. 

`replaceChildren` will only make sense if you own the parent.

Should have checked on the test folder, my bad.  I will take a look and let you know.

I doubt you will be open to it, but maybe an idea would be to give a parameter `hint` so the diff can focus on the hint provided, such hint `remove`, removal of whats not in the new list.  That way you can in some way default to the fast path on most used cases.

**Comment by titoBouzout** [comment]
Thanks, all that makes sense, I think I let myself carry on by the results I got. I am doing three passes, first to handle swapping, then for sorting and the last one for removal, not perfect but fast enough. I'm busy with something but whenever I go back to this I will experiment and post here if I found something of interest, thanks again!

**Comment by WebReflection** [comment]
@titoBouzout before *udomdiff* I had [majinbuu](https://github.com/WebReflection/majinbuu) (based on [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) for DOM nodes) and it was scanning first, producing changes, then applying these ... **slower**.

After that I had [An E.Meyers's O(ND) Based Diffing Algorithm](https://github.com/WebReflection/speedy-myers) which was inevitably also scanning once then produce changes ... **slower**.

With *udomdiff* you have **one pass** (actually 2 in the worst case scenario as the *Map* needs to be generated to have then O(1) operations later on) and I really doubt any other general purpose differ can guarantee the same average or overall performance ... I've been doing this for years and *udomdiff* is currently a **done project** to me.

That being said, of course if you manage to improve the slow path by any relevant mean without bloating the final size I will be more than welcoming your proposal/change, but it's also true that *udomdiff* competes with dozen thousand of nodes, nested or linear, and it's usually *never the bottleneck* for whatever application you are running.
